version: '3.8'
services:
  frontend:
    env_file: ./.env.pavlyuk
    container_name: aq-frontend
    build:
      context: .
      target: production
    networks:
      - aq-proxy
    ports:
      - 80:80
      - 443:443
networks:
  aq-proxy:
    external: true
