version: '3.8'
services:
  frontend:
    env_file: ./.env.production
    container_name: aq-frontend
    build:
      context: .  # Явное указание контекста
      dockerfile: ./Dockerfile.dvfu
      target: production
    networks:
      - aq-proxy
    ports:
      - "80:80"   # Всегда заключайте номера портов в кавычки
      - "443:443"  # чтобы избежать проблем с парсингом YAML
    volumes:
      - /etc/nginx/ssl:/etc/nginx/ssl  # Монтируем папку с сертификатами

networks:
  aq-proxy:
    external: true
