version: '3.8'
services:
  frontend:
    env_file: ./.env.production
    container_name: aq-frontend
    build:
      context: .
      target: production
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
networks:
  proxy:
