version: '3.8'
services:
  frontend:
    env_file: ./.env.production
    build:
      context: .
      target: production
    ports:
      - 80:80
      - 443:443
networks:
  default:
    driver: bridge
